# Generated by Django 5.1.1 on 2024-09-11 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candlestickdata',
            name='close',
            field=models.FloatField(default=50),
        ),
    ]
