# Generated by Django 5.1.1 on 2024-09-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_bardata_piedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='piedata',
            name='data',
            field=models.FloatField(default=50),
        ),
    ]
